examples/mcp-filesystem/index.ts, examples/tool-usage/calculator.ts, examples/tool-usage/index.ts, examples/tool-usage/weather.ts, package.json, pnpm-lock.yaml, src/tools/mcp/client.ts, src/tools/mcp/create-tool.ts, src/tools/mcp/index.ts, src/tools/mcp/schema-conversion.ts, src/tools/mcp/types.ts, src/tools/mcp/utils.ts
Closes https://github.com/IQAIcom/issues/issues/236 when this PR merged.
- Created mcp tool to connect to mcp server
- Some minor refactoring for tool-usage example
=> Adds MCP tool

.changeset/wild-coats-prove.md, packages/adk/src/agents/lang-graph-agent.ts, packages/adk/src/agents/llm-agent.ts, packages/adk/src/agents/loop-agent.ts, packages/adk/src/agents/parallel-agent.ts, packages/adk/src/agents/sequential-agent.ts, packages/adk/src/helpers/debug.ts, packages/adk/src/memory/persistent-memory-service.ts, packages/adk/src/models/anthropic-llm-connection.ts, packages/adk/src/models/anthropic-llm.ts, packages/adk/src/models/llm-registry.ts, packages/adk/src/models/openai-llm.ts, packages/adk/src/tools/base/base-tool.ts, packages/adk/src/tools/common/exit-loop-tool.ts, packages/adk/src/tools/common/get-user-choice-tool.ts, packages/adk/src/tools/common/google-search.ts, packages/adk/src/tools/common/load-memory-tool.ts, packages/adk/src/tools/common/transfer-to-agent-tool.ts, packages/adk/src/tools/mcp/create-tool.ts
- Adds quick fix for: add debug logs
=> add debug logs

.changeset/eleven-days-sniff.md, packages/adk/package.json, packages/adk/src/agents/lang-graph-agent.ts, packages/adk/src/agents/llm-agent.ts, packages/adk/src/agents/loop-agent.ts, packages/adk/src/agents/parallel-agent.ts, packages/adk/src/agents/sequential-agent.ts, packages/adk/src/helpers/debug.ts, packages/adk/src/helpers/logger.ts, packages/adk/src/memory/persistent-memory-service.ts, packages/adk/src/models/anthropic-llm-connection.ts, packages/adk/src/models/anthropic-llm.ts, packages/adk/src/models/llm-registry.ts, packages/adk/src/models/openai-llm.ts, packages/adk/src/tools/base/base-tool.ts, packages/adk/src/tools/common/exit-loop-tool.ts, packages/adk/src/tools/common/get-user-choice-tool.ts, packages/adk/src/tools/common/google-search.ts, packages/adk/src/tools/common/load-memory-tool.ts, packages/adk/src/tools/common/transfer-to-agent-tool.ts, packages/adk/src/tools/mcp/client.ts, packages/adk/src/tools/mcp/create-tool.ts, packages/adk/src/tools/mcp/types.ts, pnpm-lock.yaml
- Adds support for MCP Sampling request handling
- Adds new Logger class with better logging
=> Adds support for MCP sampling and cleaner debug logs

.changeset/itchy-candles-behave.md, packages/adk/src/tools/mcp/client.ts, packages/adk/src/tools/mcp/sampling-handler.ts, packages/adk/src/tools/mcp/types.ts
- Adds quick fix for: simplified sampling handler
=> simplified sampling handler

.changeset/chubby-islands-ask.md, packages/adk/src/tools/mcp/client.ts, packages/adk/src/tools/mcp/index.ts, packages/adk/src/tools/mcp/sampling-handler.ts, packages/adk/src/tools/mcp/types.ts
- Adds quick fix for: adds proper input and output conversion from LLMRequest and LLMResponse types
=> adds proper input and output conversion from LLMRequest and LLMResponse types

.changeset/shiny-socks-arrive.md, packages/adk/package.json, pnpm-lock.yaml
- Adds quick fix for: add better-sqlite3 dependency
=> add better-sqlite3 dependency

apps/docs/app/docs/[[...slug]]/page.client.tsx, apps/docs/app/docs/[[...slug]]/page.tsx, apps/docs/app/llm.txt/route.ts, apps/docs/app/llms.mdx/[[...slug]]/route.ts, apps/docs/lib/getLlmText.ts, apps/docs/next.config.mjs, apps/docs/package.json, pnpm-lock.yaml
- Add LLM Copy Button and View Options components
- Added routes for llm.txt and llms.mdx to get the llm parsable text
=> Adds support for llms.txt

.changeset/ripe-trees-create.md, packages/adk/src/tools/mcp/servers.ts
- Adds quick fix for: add coingecko-mcp-server-definition
=> add coingecko-mcp-server-definition

.changeset/real-tigers-pull.md, apps/examples/src/agent-builder-example/index.ts, packages/adk/src/agents/agent-builder.ts
Enhance session management and runner API for improved usability and flexibility, allowing for optional smart defaults and a more streamlined interaction process.
=> Refactor session management and runner for simplicity

apps/examples/src/mcp-telegram-agent/index.ts
closes https://github.com/IQAIcom/mcp-telegram/issues/5
=> create telegram agent example

apps/docs/content/docs/framework/agents/workflow-agents/loop-agents.mdx, apps/docs/content/docs/framework/agents/workflow-agents/parallel-agents.mdx, apps/docs/content/docs/framework/agents/workflow-agents/sequential-agents.mdx
*Closes https://github.com/IQAIcom/adk-ts/issues/104 when this PR merged*
- loop, sequential, parallel
- Reduced content, added examples
=> Update multi agent examples

.changeset/pink-frogs-tap.md, packages/adk/src/agents/agent-builder.ts
- Adds quick fix for: update sessionService passing to agent
=> update sessionService passing to agent

.changeset/old-wolves-do.md, apps/examples/src/shared-memory-agents/index.ts, packages/adk/src/flows/llm-flows/shared-memory.ts, packages/adk/src/flows/llm-flows/single-flow.ts, packages/adk/src/runners.ts
- Adds shared memory request processor that allows agents to access memories when using same InMemoryMemoryService
- Added an example demonstrating the same
- Save session to memoryService in runner if present
=> Create shared memory request processor

.changeset/legal-clouds-act.md, apps/examples/src/agent-tool-example/index.ts, packages/adk/src/tools/common/agent-tool.ts, packages/adk/src/tools/index.ts
- Adds quick fix for: add agent tool
=> add agent tool

.changeset/shy-eyes-drum.md, apps/examples/src/sub-agents/index.ts, packages/adk/src/agents/agent-builder.ts, packages/adk/src/agents/llm-agent.ts, packages/adk/src/flows/llm-flows/agent-transfer.ts, packages/adk/src/tools/common/transfer-to-agent-tool.ts
Update the transfer agent tool to improve efficiency and add support for sub-agents and callbacks in the agent creation process. Introduce a function declaration for better integration and usability.
=> Enhance transfer agent tool with sub-agents and callbacks

.changeset/kind-moose-learn.md, packages/adk/src/tools/base/create-tool.ts
- Adds quick fix for: zod-inference-fix
=> zod-inference-fix

.changeset/fruity-plums-march.md, packages/adk/src/tools/base/create-tool.ts
- Adds quick fix for: update create tool type
=> update create tool type

apps/docs/app/global.css
https://github.com/user-attachments/assets/3f2ac113-69d2-4b63-8a29-d44eb6945d32
- After debugging enough, found out it was just how fumadocs renders leaf side bar items with filled in pages array in `meta.json`
- Easiest solution would be just doing this on global.css
```
button:hover {
cursor: pointer;
}
```
=> Docs: Add cursor pointer on hover

.changeset/dry-impalas-stick.md, apps/docs/content/docs/mcp-servers/index.mdx, apps/docs/content/docs/mcp-servers/meta.json, apps/docs/content/docs/mcp-servers/upbit.mdx, packages/adk/src/tools/mcp/servers.ts
Added @iqai/mcp-upbit to adk-ts servers.ts file & adk-ts docs app
closes https://github.com/IQAIcom/mcp-upbit/issues/2
- Ran the docs app locally and ensure the mcp-upbit page loads 👍
N/A
=> add mcp-upbit

.changeset/icy-sloths-hammer.md, apps/starter-templates/pnpm-lock.yaml, apps/starter-templates/shade-agent/package.json, apps/starter-templates/shade-agent/src/agents/agent.ts, apps/starter-templates/shade-agent/src/agents/eth-sentiment-agent/agent.ts, apps/starter-templates/shade-agent/src/agents/eth-sentiment-agent/tools.ts, apps/starter-templates/shade-agent/src/agents/format-agent/agent.ts, apps/starter-templates/shade-agent/src/routes/transaction.ts, packages/adk-cli/src/server/services.ts
Enhance the loading mechanism to check for multiple environment files in a specified priority order, ensuring that environment variables are set only if they are not already defined. Additionally, provide warnings for any errors encountered while loading these files.
=> Improve handling of loading environment files

.changeset/purple-donkeys-begin.md, packages/adk-cli/src/commands/new.ts
- Adds quick fix for: add shade agent in template listing in cli
=> add shade agent in template listing in cli

.changeset/smart-items-train.md, packages/adk/src/agents/agent-builder.ts
- Adds .withRunConfig() option on AgentBuilder for more control over runners runAsync configuration.
=> Add withRunConfig option to AgentBuilder for runtime configuration

.changeset/busy-snails-obey.md, packages/adk/src/models/openai-llm.ts
- Adds quick fix for: support gpt 5
=> support gpt 5
